name: marp-github-actions

on: 
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Packages
        run: sudo apt-get update & sudo apt-get install jq
      
      - name: Read Conigs
        run: |
          directory=$(cat config.json | jq -r .directory)
          output_name=$(cat config.json | jq -r .output_name)
          echo "::set-output name=DIRECTORY::${directory}"
          echo "::set-output name=OUTPUT_NAME::${output_name}"
        id: config

      - name: Make Directory
        run: mkdir dest & cp -r ./git-tutorial/imgs ./dest/imgs

      - name: Setup Permission
        run: chmod -R 777 $(pwd)

      - name: Build Marp PDF
        run: docker run --rm -u root --init -v "$(pwd):/home/marp/app/" 
              -e LANG="ja_JP.UTF-8" marpteam/marp-cli ${{steps.config.outputs.DIRECTORY}}/slide.md 
              --pdf
              -o ./dest/${{steps.config.outputs.OUTPUT_NAME}}.pdf
              --allow-local-files
      - name: Build Marp HTML
        run: docker run --rm -u root --init -v "$(pwd):/home/marp/app/" 
              -e LANG="ja_JP.UTF-8" marpteam/marp-cli ${{steps.config.outputs.DIRECTORY}}/slide.md 
              --html 
              -o ./dest/${{steps.config.outputs.OUTPUT_NAME}}.html
              --allow-local-files

      - name: Upload Files Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dest

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1